# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wenwen Zhang
title: Graduate Student at University of British Columbia
email: Wenwenzhang@ece.ubc.ca
website: https://zhang-wenwen.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Zhang-Wenwen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: wenw-zhang
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Wenwen Zhang, I'm a MASc student at the University of British Columbia, Canada. 
  I am now working as a research assistant in Flexible Electronics and Energy Lab (FEEL).
  My research focuses on wearable devices and federated learning method considering large proportion of no-label data with huge data heterogeneity at different device end.
  I am very optimistic about the future of wearable devices. I believe the interdisciplinary field which connects the popular machine learning and end devices will be promising. 
  I have worked with a range of different languages (python, MATLAB, C, C++), tried different fields in Electrical Engineering field (microwave components, image process, machie learning), 
  and I am always looking forward to opportunities to work with something new.
  
  If you are interested, please download [my Resumé](https://www.google.com/) here.

content:
  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        #title: Texavie Technologies, Inc.
        description: | # this will include new lines to allow paragraphs
            W. Zhang, K. Ma, H. Zhang and H. Fu, "Design of a Compact SISL BPF With SEMCP for 5G Sub-6 GHz Bands," in IEEE Microwave and Wireless Components Letters, vol. 30, 
            no. 12, pp. 1121-1124, Dec. 2020, [doi: 10.1109/LMWC.2020.3030189.](https://ieeexplore.ieee.org/document/9240088)          
            
            A. Tashakori, W Zhang, Z. Wang, and P Servati, "SemiPFL: Personalized Semi-Supervised Federated Learning Framework for Embedded Intelligence," 
            submitted to IEEE Internet of Things Journal. 
            
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Personalized Semi-supervised Federated Learning for Embedded Intelligence
        link: https://feel.ece.ubc.ca/
        link_text: flexible Electronics and Energy Lab in Electronic and Computer Engineering Department
        #quote: >
        #  "[Flexible Electronics and Energy Lab](https://feel.ece.ubc.ca/)" in Electronic and Computer Engineering Department
        description: | # this will include new lines to allow paragraphs
          This project explores federated learning method considering large proportion of non-labeled data with significant data heterogeneity at different device end. 
          With the development of wearable sensors, people are able to collect enormous data volume from huge number of individuals. These data always come with huge
          diversity and complexity due to differences in personal habits. And it also takes expensive energy and high cost to label these data. To address these concerns, 
          federated learning is proposed to deal with the unlabeled data and data heterogeneity.
        
      - layout: top-middle
        title: Smart Knee Sleeves Based on Flexible Sensors 	
        link: https://texavie.com/
        link_text: Texavie Technologies, Inc.
        additional_links:
          - link:  https://feel.ece.ubc.ca/Flexible Electronics and Energy Lab    
            link_text: Flexible Electronics and Energy Lab 
        #quote: >
        #  [Texavie Technologies, Inc.](https://texavie.com/) & [Flexible Electronics and Energy Lab](https://feel.ece.ubc.ca/)
        description: | # this will include new lines to allow paragraphs
          This project works on lower extremity estimation & movement tracking & muscle condition monitoring by data collected from flexible sensors (stress, temperature, ect.) 
          integrated on knee braces. The emergence of these wearable devices enable the possibility to monitor personal health status by daily activities. What's more, 
          this kind of flexible sensors free people from lab environment with more comprehensive feedback on healthy detection and achieve significant cost savings.

      - layout: top-middle
        title: Wearable Sensor System for Gait Disorder Patients	
        link: http://humbl.bme.ubc.ca/
        link_text: Human Motion Biomechanics Lab & Flexible Electronics and Energy Lab](https://feel.ece.ubc.ca/
        #quote: >
        #  [Human Motion Biomechanics Lab](http://humbl.bme.ubc.ca/) & [Flexible Electronics and Energy Lab](https://feel.ece.ubc.ca/)
        description: | # this will include new lines to allow paragraphs
          This project develops real-time algorithms to predict gait parameters of patients with disorders (Parkinson, stroke & geriatric). People with impairment of injury or 
          senior age often suffer from gait disorders which may cause falls or other serious consequences during walk. To control such risks, gait parameters should be to utilized
          and tracked in daily activities to assess the severity of disease. 
                    
      - layout: top-middle
        title: Intelligent Glove with Embedded Wearable Sensors	
        link: https://feel.ece.ubc.ca/
        link_text: Texavie Technologies, Inc. & Flexible Electronics and Energy Lab
        #quote: >
        #  [Texavie Technologies, Inc.](https://texavie.com/) & [Flexible Electronics and Energy Lab](https://feel.ece.ubc.ca/)
        description: | # this will include new lines to allow paragraphs
          This project aims to reconstruct hand gesture of post-stroke patients to assess upper extremity function and help motivate recovery progress. It also has the promise
          to be developed as real-time model for VR & AR game in the future.
          
      - layout: top-middle
        title: Real-World Biomechanical Measurements of Impacts in Humans
        link: http://humbl.bme.ubc.ca/
        link_text: Human Motion Biomechanics Lab & Flexible Electronics and Energy Lab
        #quote: >
        #  [Human Motion Biomechanics Lab](http://humbl.bme.ubc.ca/) & [Flexible Electronics and Energy Lab](https://feel.ece.ubc.ca/)
        description: | # this will include new lines to allow paragraphs
          Quantifying measurement errors in wearable inertial measurement unit devices caused by soft tissue movement artifacts is important in all data collection process.
          Soft tissue movement artifacts always bring drift when measuring data from wearable sensors. And the drifts are the most frequent reason responsible for effectiveness
          of developed algorithm. However, by analyzing the different between ground truth and affected, it's possible to get rid of these influence.
          
      - layout: top-middle
        title: Auto-calibration of multi-sensors
        link: http://humbl.bme.ubc.ca/
        link_text: Human Motion Biomechanics Lab, The University of British Columbia
        #quote: >
        #  Human Motion Biomechanics Lab
        description: | # this will include new lines to allow paragraphs
          This project automatically  calibrates relative sensor locations and orientation movement during slow motions. Calibration is indispensable in wearable sensor systems
          where multiple sensors are utilized. Sensors should be calibrated and notified each other's location to cooperate in later motion detection activities. Current calibration
          system require strict standard and training to achieve purpose. To help with home-monitor goals, a calibration system working effectively during slow motion like walking
          is necessary. 
          
      - layout: top-middle
        title: Weight Bank Addition Photonic Accelerator in Neuromorphic Networks	
        link: https://mina.ubc.ca/
        link_text: Microsystems and Nanotechnology (MiNa) Lab, The University of British Columbia 
        #quote: >
        #  Human Motion Biomechanics Lab
        description: | # this will include new lines to allow paragraphs
          This project focus on designing and implementing cascaded micro-ring weight bank which reports the observations of weight addition and subtraction in 
          neuromorphic networks based on silicon on insulators (SOI).           
          
      - layout: top-middle
        title: Extended FSR Micro-Ring Modulator	
        link: https://mina.ubc.ca/
        link_text: Microsystems and Nanotechnology (MiNa) Lab, The University of British Columbia 
        #quote: >
        #  Human Motion Biomechanics Lab
        description: | # this will include new lines to allow paragraphs
          This project focus on designing and implementing parallel and cascaded ring resonators exhibiting Vernier effect and extended free spectral range (FSR). 
          Extended FSR is helpful for clean and wide band comparable to C-band which support maximum number of channels.          
          
      - layout: top-middle
        title: Dual-band Microwave Filters for 5G	
        quote: >
          Interconnection Perception Microelectronics Laboratory, Tianjin University
        description: | # this will include new lines to allow paragraphs
          This project works on designing a Self-Packaged dual bandpass filter with improved suppression for 5G sub-6 GHz applications based on the 
          Substrate Integrated Suspended Line (SISL) technology.               
          
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Texavie Technologies
        link: https://texavie.com/
        # link_text: boringcompany.com
        sub_title: R&D Intern, Hardware/Firmware and Data Processing
        caption: December 2022 - Present
        quote: >
          Texavie works on intelligent apparel for digital health and wellness
        description: | # this will include new lines to allow paragraphs
            I participated in hardware/firmware programming & testing and data processing in Texavie, mostly working with C/C++/python/MATLAB code here. Texavie cooperates with
            Flexible Electronics and Energy Lab as well. It's an amazing company where Industry-University-Academy cooperation teaching mode combines perfectly. 
         
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The University of British Columbia
        caption: 2020 - present
        sub_title: MASc Electrical and Computer Engineering
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at UBC I spend a great time learning and working. I learn most of my crucial skills that will be useful in future life such as teamwork and working to tight deadlines. 
          I thoroughly  enjoy every second in UBC and learned how important it is to lead a healthy work life balance.
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Badmiton
      - Basketball
      - Gaming
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
